### ISSUE TITLE
There is no ecmascript 7 async and promises

### ISSUE THREAD

**Issue by shavidzet** [davidkudera/google-maps-loader#38]
Does anyone need?

**Comment by smajl** [comment]
What do you have exactly on mind (usecase)? Because I was just wondering that it might be really useful to have "fail" callback. Somehow like [jQuery.getScript](https://api.jquery.com/jquery.getscript/) loads scripts. But that returns promises and seems like this project creator intentions were to remove promises altogether.

My usecase: [try to load Google Maps API] -> <fail> -> [fallback to offline solutions (e.g. OSM)]

**Comment by davidkudera** [comment]
This package used promises at the beginning. The problem was that it added some huge dependency to project + I needed (still need) to support older browsers, so I also can't simply use native promises or async.

If you'll look at the code, you'll see that it's really easy and that's why I rewrite it from coffeescript to pure js and removed all dependencies too. Now anyone can use it and it matters not what your current environment is.

But I'm not saying that I woudn't like it. :smiley: Oh and what I also like is the idea about some fail callback. Don't you want to send an pull request?

**Comment by ShavidzeT** [comment]
@davidkudera Yeap, I want to send you pull request. On my weekends I'll write code ;)

**Comment by davidkudera** [comment]
Hi, I was thinking about it again and I think that I found a solution which could be good for everyone. We can keep current code just like it is now and create new file which will contain wrapper around the current code with ES7 support. 

With this approach every developer can choose the best option for them. 

What do you think about it?

**Comment by atrauzzi** [comment]
Would love to see promises implemented in this library.  Much cleaner and can then be used with the awesome `async` keyword in TypeScript/ESwhatever.

**Comment by ShavidzeT** [comment]
@davidkudera I like your idea, wrapper is better solution. I will think about it

**Comment by davidkudera** [comment]
Hi and sorry for the long human-timeout. Promises are back :wink: 

Please check out the new version 4.1.1. It's now written in typescript and supports await/async.
