### ISSUE TITLE
Reload google maps with different libraries

### ISSUE THREAD

**Issue by categulario** [davidkudera/google-maps-loader#57]
I'm using this project to load google maps in a react app, but different views need different libraries to be loaded. The problem is, once google maps is loaded further calls to `load()` return the same already loaded google maps (without the new libraries).

Right now a call to `release()` before calling `load()` solves the problem, but I think it should be a more elegant solution.

**Comment by davidkudera** [comment]
Hi, please check out the new version 4.1.1. It's written in typescript and supports await/async.

Also, the `release()` function was here only for testing. Because of this, I removed it from the new version. There can be problems if you'll try to show eg. 2 maps on the same page with different libraries. Google maps API is stored in `window.google` and changing it dynamically can break one of the map.

Ideally, you should create some kind of factory for this library `Loader` and call it to always return the same instance of loader (with dependency injection cantainer, singleton, or other patterns).
